package com.example.sports

object FakeDatabase {
    fun sports(): MutableList<Sport>{
        val soccerSport = Sport(1, "Fútbol Soccer", "El fútbol o futbol2 (del inglés británico football, traducido como balompié) es un deporte de equipo jugado entre dos conjuntos de once jugadores cada uno, mientras los árbitros se ocupan de que las normas se cumplan correctamente. Es, ampliamente, considerado el deporte más popular del mundo, pues lo practican unas 270 millones de personas. También se le conoce como fútbol 11 por el número de jugadores de un equipo o fútbol asociación, nombre derivado de The Football Association, primera federación oficial del mundo en este deporte y que utilizó ese nombre para distinguirlo de otros deportes que incluyen la palabra «fútbol» o «futbol». En algunos países de habla inglesa, también se le conoce como soccer, abreviatura de association, puesto que el nombre de football en esos países se asocia mayoritariamente a otros deportes con esa denominación (principalmente en Estados Unidos, donde el nombre football aplica para el fútbol americano, un deporte totalmente distinto).",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Football_%28Soccer%29.JPG/1024px-Football_%28Soccer%29.JPG")
        val baseballSport = Sport(2, "Baseball", "El béisbol (del inglés baseball; de base, y ball, 'pelota'), también llamado baseball o pelota base, es un deporte de equipo jugado por dos equipos de nueve jugadores cada uno.\n" +
                "Es considerado uno de los deportes más populares en República Dominicana, Panamá, Corea del Sur, Cuba, Estados Unidos, Curazao, Aruba, Japón, Nicaragua, Puerto Rico, Taiwán, México y Venezuela, y no tan popular, pero con una cantidad importante de aficionados, en países como Canadá, Australia, Sudáfrica, Colombia, China, Países Bajos e Italia. Los países considerados potencias de este deporte se encuentran en América (Norte y el Caribe) y se juega en un gran campo cubierto completamente por césped natural o artificial, con excepción de una zona llamada línea del corredor, donde los jugadores de la ofensiva corren para alcanzar las bases ubicadas en los vértices del área cuadrangular llamada diamante, y anotar así como el área del lanzador, donde el terreno es una loma de tierra.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/A_worn-out_baseball.JPG/2470px-A_worn-out_baseball.JPG")
        val volleyballSport = Sport(3, "Volleyball", "El voleibol, vóleibol, volibol, vólibol, balonvolea o simplemente vóley (en inglés, volleyball; pronunciado /ˈvɑliˌbɔl/) es un deporte que se juega con una pelota y en el que dos equipos, integrados por seis jugadores cada uno, se enfrentan sobre un área de juego separada por una red central. El objetivo del juego es pasar el balón por encima de la red, logrando que llegue al suelo del campo contrario mientras el equipo adversario intenta impedir simultáneamente que lo consiga, forzándolo a errar en su intento. Surge una fase de ataque en un equipo cuando intenta que el balón toque el suelo del campo contrario mientras que en el otro equipo surge una fase de defensa intentando impedirlo.\n" +
                "El balón debe ser tocado o impulsado con golpes limpios, pero no puede ser parado, sujetado, retenido o acompañado. Cada equipo dispone de un máximo de tres toques para devolver el balón al campo contrario (además del contacto del bloqueo). El balón se golpea normalmente con manos y brazos. Desde hace algunos años está permitido el contacto del balón con cualquier parte del cuerpo, incluidos los pies. Una de las características más peculiares del voleibol es que los jugadores tienen que ir rotando sus posiciones a medida que van consiguiendo puntos.",
            "https://upload.wikimedia.org/wikipedia/commons/b/bf/Algeria_and_Japan_women%27s_national_volleyball_team_at_the_2012_Summer_Olympics_%287913959028%29.jpg")
        val boxingSport = Sport(4, "Boxeo", "El boxeo (del inglés boxing), también llamado a veces boxeo inglés, boxeo irlandés o pugilismo, y comúnmente conocido como box, es un deporte de contacto en el que dos contrincantes luchan utilizando únicamente sus puños con guantes, golpeando a su adversario de la cintura hacia arriba, dentro de un cuadrilátero especialmente diseñado para tal fin; la pelea se lleva a cabo en breves secuencias de lucha denominadas asaltos y de acuerdo a un preciso reglamento, el cual regula categorías de pesos y duración del encuentro, entre otros aspectos.\n" +
                "Aunque el término \"boxeo\" comúnmente se atribuye al \"boxeo inglés\", en el que solo intervienen los puños, el boxeo se ha desarrollado de diversas formas en diferentes áreas geográficas y culturas. En términos globales, el boxeo es un conjunto de deportes de combate centrados en el golpe, en el que dos oponentes se enfrentan en una pelea usando al menos los puños, y posiblemente involucrando otras acciones como patadas, codazos, rodillazos, cabezazos, dependiendo de las reglas. Algunas de las formas del deporte moderno son el boxeo inglés, el boxeo con nudillos desnudos, el kickboxing, el muay-thai, el lethwei, el savate o el sanda. Las técnicas de boxeo se han incorporado a muchas artes marciales, entrenamiento militar, autodefensa y otros deportes de combate.",
            "https://upload.wikimedia.org/wikipedia/commons/4/4d/Boxing_at_the_2018_Summer_Youth_Olympics_%E2%80%93_Girls%27_flyweight_Bronze_Medal_Bout_068.jpg")
        val tennisSport = Sport(5, "Tenis", "El tenis, también llamado tenis de campo, es un deporte de raqueta practicado sobre una pista rectangular (compuesta por distintas superficies como lo pueden ser el cemento, la tierra batida o hierba), delimitada por líneas y dividida por una red.\n" +
                "Se disputa entre dos jugadores (individuales) o entre dos parejas (dobles).\n" +
                "El objetivo principal del juego es lanzar una pelota golpeándola con la raqueta de modo que rebote en el otro lado pasando la red dentro de los límites permitidos del campo del rival, procurando que este no pueda devolverla para conseguir un segundo rebote en el suelo y darle un punto.",
            "https://upload.wikimedia.org/wikipedia/commons/3/3e/Tennis_Racket_and_Balls.jpg")
        val rugbySport = Sport(6, "Rugby", "El rugby es un deporte de evasión y contacto —con excepción de la modalidad de rugby sin contacto—, en equipo, nacido en Inglaterra. Fue en ese país donde tomó su nombre a partir de las reglas del fútbol elaboradas en el colegio de la ciudad de Rugby (Rugby School) en el siglo xix.\n" +
                "El rugby se practica a nivel internacional en todos los continentes, aunque ha alcanzado un importante grado de desarrollo en las naciones que conforman las islas británicas (Escocia, Gales, Inglaterra, Irlanda e Irlanda del Norte), así como en Australia, Fiyi, Nueva Zelanda, Samoa, Sudáfrica, Tonga, Uruguay, Argentina y Francia.\n" +
                "En otros países tiene variados grados de popularidad y competitividad internacional. En África también es popular, por influencia inglesa, en Namibia, Kenia y Zimbabue, y por influencia francesa en Túnez, Costa de Marfil, Madagascar y Marruecos. En América se practica principalmente en Argentina—participante del Rugby Championship—, donde tiene gran arraigo y cuya selección ha logrado importantes logros internacionales; asimismo tiene cierta popularidad en otros países americanos, como Brasil, Canadá, Uruguay, Chile y Estados Unidos. En Asia, el equipo más destacado es el de Japón. En el resto de Europa, se destaca Italia, que participa en el Torneo de las Seis Naciones. Igualmente está difundido en otros países del continente europeo, sobre todo en Portugal, España y en países del este de Europa, como Rumania, Georgia o Rusia. En Oceanía, por influencia australiana y neozelandesa, el rugby es un deporte muy popular en Fiyi, Tonga y Samoa, cuna de jugadores destacados en el ámbito internacional.",
            "https://upload.wikimedia.org/wikipedia/commons/6/6a/New_Zealand_national_rugby_20191101d4.jpg")
        val hockeySport = Sport(7, "Hokey", "El hockey (raramente adaptado como jóquey) es una familia de deportes originada en Inglaterra a mediados del siglo XVIII en la cual dos equipos compiten para llevar una pelota de un material duro (plástico) o un disco de corcho a la portería contraria para anotar puntos con la ayuda de un bastón largo llamado \"palo de hockey\" (stick en inglés, bâton en francés).",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/2020-01-21_Ice_hockey_at_the_2020_Winter_Youth_Olympics_%E2%80%93_Women%27s_tournament_%E2%80%93_Gold_Medal_Game_%28Martin_Rulsch%29_068.jpg/2560px-2020-01-21_Ice_hockey_at_the_2020_Winter_Youth_Olympics_%E2%80%93_Women%27s_tournament_%E2%80%93_Gold_Medal_Game_%28Martin_Rulsch%29_068.jpg")
        val golfSport = Sport(8, "Golf", "El golf es un deporte cuyo objetivo es introducir una bola en los hoyos que están distribuidos en el campo con el menor número de golpes, utilizando para cada tipo de golpe uno de entre un conjunto de palos ligeramente diferentes entre sí, ya que la cabeza del palo tiene ángulos distintos, al igual que las varillas tienen longitudes diferentes. A menor número de grados de inclinación, mayor longitud de la varilla y, por lo tanto, más distancia. Como máximo se pueden llevar catorce palos y como mínimo cinco palos. Al que practica el golf se le denomina golfista.\n" +
                "En 1744, se fundó la primera asociación de jugadores en Escocia, y en 1745, también en Gran Bretaña, se creó la primera reglamentación del golf. Las primeras asociaciones de golf fueron la Honourable Company of Edinburgh Golfers (1744) y The Royal and Ancient Golf Club of St Andrews (1754).",
            "https://upload.wikimedia.org/wikipedia/commons/d/d9/Golf_ball_2.jpg")
        val chessSport = Sport(9, "Chess", "El ajedrez es un juego de tablero entre dos contrincantes en el que cada uno dispone al inicio de 16 piezas móviles que se colocan sobre un tablero dividido en 64 casillas o escaques. En su versión de competición, está considerado como un deporte, aunque en la actualidad tiene claramente una dimensión social, educativa y terapéutica.\n" +
                "Se juega sobre un tablero cuadriculado de 8×8 casillas (también llamadas escaques), alternadas en colores blanco y negro, que constituyen las 64 posibles posiciones de las piezas para el desarrollo del juego. Al principio del juego cada jugador tiene dieciséis piezas: un rey, una dama, dos alfiles, dos caballos, dos torres y ocho peones. Se trata de un juego de estrategia en el que el objetivo es «derrocar» al rey del oponente. Esto se hace amenazando la casilla que ocupa el rey con alguna de las piezas propias sin que el otro jugador pueda proteger a su rey interponiendo una pieza entre su rey y la pieza que lo amenaza, mover su rey a un escaque libre o capturar a la pieza que lo está amenazando, lo que trae como resultado el jaque mate y el fin de la partida.",
            "https://upload.wikimedia.org/wikipedia/commons/8/8c/Chess_Large.JPG")
        return mutableListOf(soccerSport, baseballSport, volleyballSport, boxingSport, tennisSport,
            rugbySport, hockeySport, golfSport, chessSport)
    }
}